"use client";
import{useEffect,useState}from"react";import{supabase}from"../lib/supabase";
export default function Home(){const db=supabase();const[d,setD]=useState<any>({leagues:0,teams:0,players:0,matches:0,live:[],upcoming:[],results:[],scorers:[],news:[]});const[loading,setLoading]=useState(true);
useEffect(()=>{if(!db){setLoading(false);return}Promise.all([
db.from("leagues").select("id",{count:"exact",head:true}).eq("is_active",true),db.from("teams").select("id",{count:"exact",head:true}),db.from("players").select("id",{count:"exact",head:true}),db.from("matches").select("id",{count:"exact",head:true}),
db.from("matches").select("id,scheduled_at,status,home_score,away_score,round_name,home_team:teams!matches_home_team_id_fkey(name),away_team:teams!matches_away_team_id_fkey(name),leagues(name)").eq("status","live").order("scheduled_at",{ascending:true}).limit(6),
db.from("matches").select("id,scheduled_at,status,round_name,home_team:teams!matches_home_team_id_fkey(name),away_team:teams!matches_away_team_id_fkey(name),leagues(name)").eq("status","scheduled").order("scheduled_at",{ascending:true}).limit(5),
db.from("matches").select("id,scheduled_at,status,home_score,away_score,round_name,home_team:teams!matches_home_team_id_fkey(name),away_team:teams!matches_away_team_id_fkey(name),leagues(name)").eq("status","finished").order("scheduled_at",{ascending:false}).limit(5),
db.from("competition_top_scorers").select("player_id,player_name,team_name,goals").order("goals",{ascending:false}).limit(5),
db.from("news").select("id,title,category,published_at,slug").lte("published_at",new Date().toISOString()).order("published_at",{ascending:false}).limit(5)
]).then(([l,t,p,m,live,u,res,s,n])=>{setD({leagues:l.count||0,teams:t.count||0,players:p.count||0,matches:m.count||0,live:live.data||[],upcoming:u.data||[],results:res.data||[],scorers:s.data||[],news:n.data||[]});setLoading(false)})},[]);
const cards=[["Mashindano",d.leagues,"/competitions"],["Timu",d.teams,"/teams"],["Wachezaji",d.players,"/players"],["Mechi",d.matches,"/matches"]];
const match=(m:any)=> <a className="match" href={"/matches/"+m.id} key={m.id}><div><b>{m.home_team?.name||"Home"}</b><small>{m.scheduled_at?new Date(m.scheduled_at).toLocaleString("sw-TZ"):"—"}</small></div><strong>{m.status==="finished"?m.home_score+" - "+m.away_score:m.status==="live"?m.home_score+" - "+m.away_score:"VS"}</strong><div className="right"><b>{m.away_team?.name||"Away"}</b><small>{m.round_name||m.leagues?.name||"Match"}</small></div></a>;
return <main className="shell"><header className="topbar"><div className="brand">AFRO <span>SPORT</span></div><nav><a href="/">Dashboard</a><a href="/competitions">Mashindano</a><a href="/teams">Timu</a><a href="/players">Wachezaji</a><a href="/matches">Mechi</a><a className="admin" href="/admin">Admin</a></nav></header><section className="hero"><div><p className="eyebrow">AFRICAN FOOTBALL PLATFORM</p><h1>Mpira wa Afrika,<br/><span>sehemu moja.</span></h1><p className="lead">Fuata ligi, vikundi, play-off, knockout, matokeo, standings na wafungaji bora.</p></div><div className="hero-ball">⚽</div></section><section className="stats">{cards.map(([label,value,href])=><a className="stat" href={href as string} key={label as string}><small>{label}</small><strong>{loading?"—":Number(value).toLocaleString()}</strong><span>→</span></a>)}</section><section className="grid"><div className="panel"><div className="panel-head"><h2>🔴 Live</h2><a href="/matches">Ona zote</a></div>{d.live.length?d.live.map(match):<div className="empty">Hakuna mechi live sasa.</div>}<div className="panel-head"><h2>Mechi zijazo</h2></div>{d.upcoming.length?d.upcoming.map(match):<div className="empty">Hakuna mechi zijazo.</div>}</div><div className="panel"><div className="panel-head"><h2>Matokeo ya mwisho</h2></div>{d.results.length?d.results.map(match):<div className="empty">Hakuna matokeo bado.</div>}<div className="panel-head"><h2>Top Scorers</h2><a href="/players">Wachezaji</a></div>{d.scorers.length?d.scorers.map((s:any)=><div className="mini-row" key={s.player_id}><a href={"/players/"+s.player_id}><b>{s.player_name}</b></a><span>{s.team_name}</span><strong>{s.goals} ⚽</strong></div>):<div className="empty">Hakuna wafungaji bado.</div>}</div></section><section className="panel"><div className="panel-head"><h2>Habari mpya</h2><a href="/news">Zote</a></div>{d.news.length?d.news.map((n:any)=><article key={n.id}><span>{n.category||"AFRO SPORT"}</span><h3>{n.title}</h3><p>{n.published_at?new Date(n.published_at).toLocaleDateString("sw-TZ"):""}</p></article>):<div className="empty">Hakuna habari zilizochapishwa bado.</div>}</section></main>}