"use client";
import {useEffect,useState}from"react";
import {useParams}from"next/navigation";
import {supabase}from"../../../lib/supabase";

export default function MatchPage(){
 const {id}=useParams<{id:string}>(),db=supabase();
 const [match,setMatch]=useState<any>(null),[events,setEvents]=useState<any[]>([]),[loading,setLoading]=useState(true);
 async function load(){if(!db||!id)return;const {data}=await db.from("matches").select("*,home_team:teams!matches_home_team_id_fkey(name,logo_url),away_team:teams!matches_away_team_id_fkey(name,logo_url),leagues(name),competition_stages(name)").eq("id",id).single();setMatch(data);const {data:ev}=await db.from("match_events").select("*,players(name),teams(name)").eq("match_id",id).order("minute",{ascending:true}).order("created_at",{ascending:true});setEvents(ev||[]);setLoading(false)}
 useEffect(()=>{load();if(!db||!id)return;const ch=db.channel("live-match-"+id).on("postgres_changes",{event:"*",schema:"public",table:"matches",filter:"id=eq."+id},load).on("postgres_changes",{event:"*",schema:"public",table:"match_events",filter:"match_id=eq."+id},load).subscribe();return()=>{db.removeChannel(ch)}},[id]);
 if(loading)return <main className="page"><div className="empty">Inapakia mechi...</div></main>;
 if(!match)return <main className="page"><div className="empty">Mechi haikupatikana.</div></main>;
 const label=(e:any)=>({goal:"⚽ Goal",penalty_scored:"🥅 Penalty",penalty_missed:"❌ Penalty missed",own_goal:"⚽ Own goal",yellow_card:"🟨 Yellow card",red_card:"🟥 Red card",substitution:"🔄 Substitution",assist:"🎯 Assist",var:"📺 VAR"}[e.event_type]||e.event_type);
 return <main className="page"><div className="page-head"><a href="/matches">← Mechi</a><h1>{match.home_team?.name} vs {match.away_team?.name}</h1><p>{match.leagues?.name||"Competition"} · {match.competition_stages?.name||match.round_name||"Match"}</p></div><section className="builder-card match-live-card"><div className="match-live-status">{match.status==="live"?"🔴 LIVE":match.status==="finished"?"FT":String(match.status||"scheduled").toUpperCase()}</div><div className="live-score"><div><strong>{match.home_team?.name}</strong></div><div className="score">{match.status==="scheduled"?"VS":`${match.home_score??0} - ${match.away_score??0}`}</div><div><strong>{match.away_team?.name}</strong></div></div>{match.status==="finished"&&(match.home_penalties!=null||match.away_penalties!=null)&&<p className="muted">Penalties: {match.home_penalties??0} - {match.away_penalties??0}</p>}<p className="muted">{match.scheduled_at?new Date(match.scheduled_at).toLocaleString("sw-TZ"):"—"}{match.venue?" · "+match.venue:""}</p></section><section className="builder-card"><h2>Match Events</h2><div className="mini-list">{events.map((e:any)=><div className="mini-row" key={e.id}><b>{e.minute??"—"}'</b><span>{label(e)}</span><span>{e.players?.name||"—"}</span><span>{e.teams?.name||"—"}</span><span>{e.details||""}</span></div>)}{!events.length&&<div className="empty">Hakuna matukio bado.</div>}</div></section></main>
}